### ISSUE TITLE
SettingWithCopyWarning

### ISSUE THREAD

**Issue by ardref** [jhwang1992/network-visualization#7]
/bin/python3 /home/user/projects/powerpedia-dockeruser@user-N56VJ:~/projects/powerpedia-docker/network-visualization$ /bin/python3 /home/user/projects/powerpedia-docker/network-visualization/app.py
/home/user/projects/powerpedia-docker/network-visualization/app.py:34: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edge1['Datetime'][index] = datetime.strptime(edge1['Date'][index], '%d/%m/%Y')
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "/home/user/projects/powerpedia-docker/network-visualization/app.py", line 304, in <module>
    app.run_server(debug=True)
  File "/home/user/.local/lib/python3.8/site-packages/dash/dash.py", line 2033, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 920, in run
![Screenshot from 2022-01-07 18-37-16](https://user-images.githubusercontent.com/75689892/148590904-ff68e64a-7b0e-4d33-9f46-dd912015a1a4.png)

    run_simple(t.cast(str, host), port, self, **options)
  File "/home/user/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 984, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
user@user-N56VJ:~/projects/powerpedia-docker/network-visualization$

**Comment by ardref** [comment]
Sorry, but this is just a warning. The real issue of course is with "OSError: [Errno 98] Address already in use".

This seems to be an issue with Dash, and a previous instance running. I cleared the relevant processes after reading https://stackoverflow.com/questions/19159771/recovering-from-zmq-error-zmqerror-address-already-in-use, and the thing works now!

I am not sure how a Zombie zmq/dash process was left running, so I am leaving this Issue here for others to consider.
